name: Nodejs App CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code 
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t nodejs-image .  

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Image to Docker Hub
      run: |
        docker tag nodejs-image ${{ secrets.DOCKER_USERNAME }}/nodejs-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-image:latest


  setup:

    runs-on: ubuntu-latest
    needs: build 
    steps:
    - name: Set up Python and Install Ansible
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install ansible

    - name: Run Ansible Playbook
      run: ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

  deploy:

    runs-on: ubuntu-latest
    needs: setup 
    steps:

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-image:latest
          sudo docker stop nodejs-app || true
          sudo docker rm nodejs-app || true
          sudo docker run -d -p 3000:3000 --name=nodejs-app ${{ secrets.DOCKER_USERNAME }}/nodejs-image:latest
          sudo docker ps
