name: Nodejs App CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code 
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t nodejs-image .  

    - name: Show all images
      run: docker images  

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag nodejs-image ${{ secrets.DOCKER_USERNAME }}/nodejs-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-image:latest
